[package]
name = "kronello-eval"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
kronello-animation = { path = "../kronello-animation" }
kronello-model = { path = "../kronello-model" }
kronello-time = { path = "../kronello-time" }
thiserror = "2"

[lints]
workspace = true
