#!/usr/bin/env python3
"""Build and verify the visual preview of the GUI design system.

The preview lives in docs/design-system/preview/. Its HTML pages render the
components and screens from docs/design-system/ with values generated from
tokens.json, so they can be opened from file:// and screenshotted again.

Usage:
    python3 scripts/design_preview.py render        # regenerate tokens.css, tokens.js, icons.js
    python3 scripts/design_preview.py check         # verify generated files, icons and font coverage
    python3 scripts/design_preview.py vendor-icons  # copy the icons listed in icons.md from pinned lucide-static
    python3 scripts/design_preview.py fonts         # subset pinned Noto fonts (needs pyftsubset + brotli)
    python3 scripts/design_preview.py screenshots   # render images/ with headless Chrome

`check` and `render` use only the standard library. `fonts` needs fontTools
(pyftsubset) with brotli; `screenshots` needs Google Chrome or Chromium
(override the binary with the CHROME environment variable).
"""

import base64
import hashlib
import html
import io
import json
import os
import re
import shutil
import subprocess
import sys
import tarfile
import tempfile
import time
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DESIGN = ROOT / "docs" / "design-system"
TOKENS = DESIGN / "tokens.json"
ICON_DOC = DESIGN / "icons.md"
PREVIEW = DESIGN / "preview"
ASSETS = PREVIEW / "assets"
ICON_DIR = ASSETS / "icons"
FONT_DIR = ASSETS / "fonts"
IMAGES = PREVIEW / "images"
CACHE = ROOT / "target" / "design-preview"

GENERATED_HEADER = "Generated by scripts/design_preview.py from docs/design-system/{source}. Do not edit."

LUCIDE = {
    "version": "1.51.0",
    "url": "https://registry.npmjs.org/lucide-static/-/lucide-static-1.51.0.tgz",
    "sha256": "6936026d1512256483161ae999982e3be3d5d74226996c4ec7447e901726a2d8",
}

GOOGLE_FONTS_COMMIT = "9710da1eacb3be272583c3224dcb70f9da6eadbb"
FONTS = [
    {
        "family": "Noto Sans JP",
        "output": "NotoSansJP-subset.woff2",
        "license": "OFL-NotoSansJP.txt",
        "path": "ofl/notosansjp/NotoSansJP%5Bwght%5D.ttf",
        "sha256": "c2f3b4d463500a2ddcd3849cded1fceeb9fd6d1c32e6cbecd568453ba50fc68f",
        "license_path": "ofl/notosansjp/OFL.txt",
        "coverage": "text",
    },
    {
        "family": "Noto Sans Mono",
        "output": "NotoSansMono-subset.woff2",
        "license": "OFL-NotoSansMono.txt",
        "path": "ofl/notosansmono/NotoSansMono%5Bwdth,wght%5D.ttf",
        "sha256": "2cb2adb378a8f574213e23df697050b83c54c27df465a2015552740b2769a081",
        "license_path": "ofl/notosansmono/OFL.txt",
        "coverage": "latin",
    },
]
SUBSET_LIST = FONT_DIR / "subset-chars.txt"

# Always kept in the Japanese subset so small edits do not need a re-subset.
BASE_RANGES = [
    (0x20, 0x7E),      # ASCII
    (0xA0, 0xFF),      # Latin-1 (×, ·, ©)
    (0x2010, 0x2027),  # dashes, quotes, bullets, ellipsis
    (0x2190, 0x2193),  # arrows
    (0x2212, 0x2212),  # minus
    (0x2318, 0x2318),  # ⌘
    (0x2325, 0x2325),  # ⌥
    (0x21E7, 0x21E7),  # ⇧
    (0x3000, 0x301F),  # CJK punctuation
    (0x3041, 0x3096),  # hiragana
    (0x309B, 0x309E),
    (0x30A1, 0x30FE),  # katakana
    (0xFF01, 0xFF5E),  # fullwidth forms
]
MONO_RANGES = [(0x20, 0x7E), (0xA0, 0xFF), (0x2010, 0x2027), (0x2190, 0x2193), (0x2212, 0x2212)]

# Screens: (image name, page, query, themes), captured at 1440×900. Pages come in both
# themes; state variants only in the default Dark theme to keep the repository small.
SCREENS = [
    ("welcome", "screens/welcome.html", "", ("dark", "light")),
    ("edit", "screens/edit.html", "", ("dark", "light")),
    ("motion", "screens/motion.html", "", ("dark", "light")),
    ("motion-curve-editor", "screens/motion.html", "state=curve", ("dark", "light")),
    ("template", "screens/template.html", "", ("dark", "light")),
    ("export", "screens/export.html", "", ("dark", "light")),
    ("state-undo-conflict", "screens/motion.html", "state=undo-conflict", ("dark",)),
    ("state-revision-conflict", "screens/motion.html", "state=revision-conflict", ("dark",)),
    ("state-adapter-unavailable", "screens/motion.html", "state=adapter-unavailable", ("dark",)),
    ("state-evaluation-error", "screens/motion.html", "state=evaluation-error", ("dark",)),
    ("state-selection-deleted", "screens/motion.html", "state=selection-deleted", ("dark",)),
    ("state-safe-mode", "screens/motion.html", "state=safe-mode", ("dark",)),
    ("state-asset-missing", "screens/edit.html", "state=asset-missing", ("dark",)),
]
SCREEN_SIZE = (1440, 900)
THEMES = ["dark", "light"]
COMPONENT_WIDTH = 1040
FOUNDATIONS_WIDTH = 1200
SCALE = 2


def fail(message):
    print(f"error: {message}", file=sys.stderr)
    sys.exit(1)


# ---------- tokens ----------


def load_tokens():
    return json.loads(TOKENS.read_text(encoding="utf-8"))


def render_tokens_css(tokens):
    color = tokens["color"]
    themes = [theme["id"] for theme in color["themes"]]
    lines = [f"/* {GENERATED_HEADER.format(source='tokens.json')} */", ""]
    for index, theme in enumerate(themes):
        selector = f':root[data-theme="{theme}"]'
        if index == 0:
            selector = f":root,\n{selector}"
        lines.append(f"{selector} {{")
        lines.append(f"  color-scheme: {theme};")
        for token in color["tokens"]:
            lines.append(f"  --{token['name']}: {token['value'][theme]};")
        for token in tokens["shadow"]["tokens"]:
            lines.append(f"  --{token['name']}: {token['value'][theme]};")
        lines.append("}")
        lines.append("")
    lines.append(":root {")
    for name, family in tokens["type"]["families"].items():
        lines.append(f"  --font-{name}: {family};")
    for group in tokens["type"]["groups"]:
        for style in group["styles"]:
            lines.append(
                f"  --font-{style['name']}: {style['fontWeight']} {style['fontSize']}/{style['lineHeight']} var(--font-{group['family']});"
            )
            lines.append(f"  --tracking-{style['name']}: {style.get('letterSpacing', 'normal')};")
    for section in ("spacing", "size", "radius"):
        for token in tokens[section]["tokens"]:
            lines.append(f"  --{token['name']}: {token['value']};")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def render_tokens_js(tokens):
    body = json.dumps(tokens, ensure_ascii=False, indent=2)
    return f"/* {GENERATED_HEADER.format(source='tokens.json')} */\nwindow.KRONELLO_TOKENS = {body};\n"


# ---------- icons ----------


def icon_names_from_doc():
    names = set()
    for line in ICON_DOC.read_text(encoding="utf-8").splitlines():
        if not line.startswith("|") or line.startswith("|---"):
            continue
        cells = line.strip("|").split("|")
        if len(cells) < 2:
            continue
        for name in re.findall(r"`([a-z0-9-]+)`", cells[1]):
            if not name.startswith("kind-") and name != "danger":
                names.add(name)
    return names


SVG_COMMENT = re.compile(r"<!--.*?-->", re.S)


def compact_svg(source):
    svg = SVG_COMMENT.sub("", source).strip()
    svg = re.sub(r"\s*\n\s*", " ", svg)
    svg = re.sub(r"\s+/>", "/>", svg)
    svg = re.sub(r"\s+>", ">", svg)
    return svg


def render_icons_js():
    entries = {}
    for path in sorted(ICON_DIR.glob("*.svg")):
        entries[path.stem] = compact_svg(path.read_text(encoding="utf-8"))
    body = json.dumps(entries, ensure_ascii=False, indent=0, sort_keys=True)
    header = GENERATED_HEADER.format(source="preview/assets/icons/*.svg")
    return f"/* {header} Lucide {LUCIDE['version']}, ISC: see icons/LICENSE. */\nwindow.KRONELLO_ICONS = {body};\n"


# ---------- generated outputs ----------


def generated_outputs():
    tokens = load_tokens()
    return {
        ASSETS / "tokens.css": render_tokens_css(tokens),
        ASSETS / "tokens.js": render_tokens_js(tokens),
        ASSETS / "icons.js": render_icons_js(),
    }


def cmd_render():
    for path, content in generated_outputs().items():
        path.write_text(content, encoding="utf-8")
        print(f"wrote {path.relative_to(ROOT)}")


# ---------- check ----------


def preview_sources():
    files = sorted(PREVIEW.rglob("*.html"))
    files += [p for p in sorted(ASSETS.glob("*.js")) if p.name != "icons.js"]
    return files


def used_icons():
    used = {}
    for path in preview_sources():
        for name in re.findall(r'data-icon="([a-z0-9-]+)"', path.read_text(encoding="utf-8")):
            used.setdefault(name, set()).add(path.relative_to(PREVIEW).as_posix())
    return used


def text_characters(paths):
    chars = set()
    for path in paths:
        text = path.read_text(encoding="utf-8")
        if path.suffix == ".html":
            text = html.unescape(text)
        chars.update(ch for ch in text if not ch.isspace())
    return chars


def required_characters():
    return text_characters(preview_sources() + [TOKENS])


def char_ranges(ranges):
    return {chr(code) for start, end in ranges for code in range(start, end + 1)}


def cmd_check():
    errors = []
    for path, expected in generated_outputs().items():
        if not path.exists() or path.read_text(encoding="utf-8") != expected:
            errors.append(f"{path.relative_to(ROOT)} is stale; run `python3 scripts/design_preview.py render`")

    documented = icon_names_from_doc()
    vendored = {p.stem for p in ICON_DIR.glob("*.svg")}
    for name in sorted(documented - vendored):
        errors.append(f"icon `{name}` is listed in icons.md but not vendored; run `vendor-icons`")
    for name in sorted(vendored - documented):
        errors.append(f"icon `{name}` is vendored but not listed in icons.md")
    for name, pages in sorted(used_icons().items()):
        if name not in documented:
            errors.append(f"icon `{name}` used in {', '.join(sorted(pages))} is not listed in icons.md")
    if not (ICON_DIR / "LICENSE").exists():
        errors.append("preview/assets/icons/LICENSE is missing")

    for font in FONTS:
        if not (FONT_DIR / font["output"]).exists():
            errors.append(f"font {font['output']} is missing; run `fonts`")
        if not (FONT_DIR / font["license"]).exists():
            errors.append(f"font license {font['license']} is missing; run `fonts`")
    if SUBSET_LIST.exists():
        covered = set(SUBSET_LIST.read_text(encoding="utf-8"))
        missing = sorted(required_characters() - covered)
        if missing:
            errors.append("characters not covered by the subset fonts (run `fonts`): " + "".join(missing))
    else:
        errors.append("preview/assets/fonts/subset-chars.txt is missing; run `fonts`")

    if errors:
        for error in errors:
            print(f"error: {error}", file=sys.stderr)
        sys.exit(1)
    print(f"design preview OK ({len(vendored)} icons, {len(generated_outputs())} generated files)")


# ---------- downloads ----------


def download(url, sha256, name):
    CACHE.mkdir(parents=True, exist_ok=True)
    destination = CACHE / name
    if destination.exists() and hashlib.sha256(destination.read_bytes()).hexdigest() == sha256:
        return destination.read_bytes()
    if not url.startswith("https://"):
        fail(f"refusing non-HTTPS download: {url}")
    request = urllib.request.Request(url, headers={"User-Agent": "kronello-design-preview/1"})
    with urllib.request.urlopen(request, timeout=120) as response:
        data = response.read()
    digest = hashlib.sha256(data).hexdigest()
    if digest != sha256:
        fail(f"SHA-256 mismatch for {url}: {digest}")
    destination.write_bytes(data)
    return data


def cmd_vendor_icons():
    data = download(LUCIDE["url"], LUCIDE["sha256"], f"lucide-static-{LUCIDE['version']}.tgz")
    names = icon_names_from_doc()
    with tarfile.open(fileobj=io.BytesIO(data), mode="r:gz") as archive:
        package = json.load(archive.extractfile("package/package.json"))
        if package["version"] != LUCIDE["version"]:
            fail(f"unexpected lucide-static version {package['version']}")
        members = {m.name: m for m in archive.getmembers()}
        missing = [n for n in sorted(names) if f"package/icons/{n}.svg" not in members]
        if missing:
            fail("icons not found in lucide-static: " + ", ".join(missing))
        if ICON_DIR.exists():
            shutil.rmtree(ICON_DIR)
        ICON_DIR.mkdir(parents=True)
        for name in sorted(names):
            (ICON_DIR / f"{name}.svg").write_bytes(archive.extractfile(f"package/icons/{name}.svg").read())
        (ICON_DIR / "LICENSE").write_bytes(archive.extractfile("package/LICENSE").read())
    print(f"vendored {len(names)} icons from lucide-static {LUCIDE['version']}")
    cmd_render()


def cmd_fonts():
    pyftsubset = shutil.which("pyftsubset")
    if not pyftsubset:
        fail("pyftsubset not found; install fontTools with brotli (pip install 'fonttools[woff]')")
    FONT_DIR.mkdir(parents=True, exist_ok=True)
    text_chars = required_characters() | char_ranges(BASE_RANGES)
    base = f"https://raw.githubusercontent.com/google/fonts/{GOOGLE_FONTS_COMMIT}/"
    for font in FONTS:
        data = download(base + font["path"], font["sha256"], Path(font["path"]).name.replace("%5B", "[").replace("%5D", "]"))
        license_text = urllib.request.urlopen(base + font["license_path"], timeout=60).read()
        (FONT_DIR / font["license"]).write_bytes(license_text)
        chars = text_chars if font["coverage"] == "text" else char_ranges(MONO_RANGES)
        with tempfile.TemporaryDirectory() as tmp:
            source = Path(tmp) / "source.ttf"
            source.write_bytes(data)
            text_file = Path(tmp) / "chars.txt"
            text_file.write_text("".join(sorted(chars)), encoding="utf-8")
            subprocess.run(
                [
                    pyftsubset, str(source), f"--text-file={text_file}", "--flavor=woff2",
                    "--layout-features=*", "--no-hinting", "--desubroutinize",
                    f"--output-file={FONT_DIR / font['output']}",
                ],
                check=True,
            )
        print(f"wrote {(FONT_DIR / font['output']).relative_to(ROOT)} ({(FONT_DIR / font['output']).stat().st_size} bytes)")
    covered = font_coverage(pyftsubset, [FONT_DIR / font["output"] for font in FONTS])
    missing = sorted(required_characters() - covered)
    if missing:
        fail("characters not in Noto Sans JP / Noto Sans Mono; replace them in the preview: " + "".join(missing))
    SUBSET_LIST.write_text("".join(sorted(ch for ch in covered if not ch.isspace())) + "\n", encoding="utf-8")
    print(f"wrote {SUBSET_LIST.relative_to(ROOT)} ({len(covered)} characters)")


def font_coverage(pyftsubset, paths):
    """Read the cmap of the subset fonts with the Python that runs pyftsubset (it has fontTools)."""
    first_line = Path(pyftsubset).read_text(encoding="utf-8", errors="replace").splitlines()[0]
    python = first_line[2:].strip() if first_line.startswith("#!") else sys.executable
    script = (
        "import sys\nfrom fontTools.ttLib import TTFont\ncodes=set()\n"
        "for path in sys.argv[1:]:\n    codes.update(TTFont(path).getBestCmap())\n"
        "print(' '.join(map(str, sorted(codes))))\n"
    )
    output = subprocess.run([*python.split(), "-c", script, *map(str, paths)], check=True, capture_output=True, text=True).stdout
    return {chr(int(code)) for code in output.split()}


# ---------- screenshots ----------


def chrome_binary():
    candidates = [os.environ.get("CHROME")] if os.environ.get("CHROME") else []
    candidates += [
        "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome",
        "/Applications/Chromium.app/Contents/MacOS/Chromium",
        shutil.which("google-chrome"), shutil.which("chromium"), shutil.which("chromium-browser"),
    ]
    for candidate in candidates:
        if candidate and Path(candidate).exists():
            return candidate
    fail("Chrome not found; set CHROME to a Chrome or Chromium binary")


CHROME_FLAGS = [
    "--headless", "--disable-gpu", "--hide-scrollbars", "--no-first-run", "--no-default-browser-check",
    "--disable-background-networking", "--disable-sync", "--disable-extensions", "--mute-audio",
    "--force-color-profile=srgb", "--font-render-hinting=none", "--allow-file-access-from-files",
]


class Chrome:
    """Minimal Chrome DevTools Protocol client over --remote-debugging-pipe (standard library only)."""

    def __init__(self, binary, profile):
        to_chrome_r, self._to_chrome = os.pipe()
        self._from_chrome, from_chrome_w = os.pipe()

        def wire_pipes():
            # Chrome reads commands from fd 3 and writes replies to fd 4.
            read_end, write_end = os.dup(to_chrome_r), os.dup(from_chrome_w)
            os.dup2(read_end, 3)
            os.dup2(write_end, 4)

        self._process = subprocess.Popen(
            [binary, *CHROME_FLAGS, "--remote-debugging-pipe", f"--user-data-dir={profile}", "about:blank"],
            pass_fds=(3, 4), preexec_fn=wire_pipes,
            stdin=subprocess.DEVNULL, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
        )
        os.close(to_chrome_r)
        os.close(from_chrome_w)
        self._buffer = b""
        self._next_id = 0
        self._events = []
        targets = self.call("Target.getTargets")["targetInfos"]
        page = next(t for t in targets if t["type"] == "page")
        self._session = self.call("Target.attachToTarget", targetId=page["targetId"], flatten=True)["sessionId"]
        self.call("Page.enable", session=True)

    def _read_message(self, deadline):
        while b"\0" not in self._buffer:
            if time.monotonic() > deadline:
                fail("timed out waiting for Chrome")
            chunk = os.read(self._from_chrome, 1 << 20)
            if not chunk:
                fail("Chrome closed the DevTools pipe")
            self._buffer += chunk
        message, self._buffer = self._buffer.split(b"\0", 1)
        return json.loads(message)

    def call(self, method, session=False, timeout=60, **params):
        self._next_id += 1
        message = {"id": self._next_id, "method": method, "params": params}
        if session:
            message["sessionId"] = self._session
        os.write(self._to_chrome, json.dumps(message).encode() + b"\0")
        deadline = time.monotonic() + timeout
        while True:
            reply = self._read_message(deadline)
            if reply.get("id") == self._next_id:
                if "error" in reply:
                    fail(f"{method}: {reply['error'].get('message')}")
                return reply.get("result", {})
            self._events.append(reply)

    def wait_event(self, method, timeout=60):
        deadline = time.monotonic() + timeout
        while True:
            for index, event in enumerate(self._events):
                if event.get("method") == method:
                    return self._events.pop(index)
            self._events.append(self._read_message(deadline))

    def evaluate(self, expression):
        result = self.call("Runtime.evaluate", session=True, expression=expression, awaitPromise=True, returnByValue=True)
        if "exceptionDetails" in result:
            fail(f"page script failed: {result['exceptionDetails'].get('text')}")
        return result["result"].get("value")

    def close(self):
        try:
            self.call("Browser.close", timeout=10)
        except SystemExit:
            pass
        try:
            self._process.wait(timeout=10)
        except subprocess.TimeoutExpired:
            self._process.kill()
        os.close(self._to_chrome)
        os.close(self._from_chrome)


READY = """new Promise(resolve => {
  const poll = () => document.documentElement.dataset.ready
    ? requestAnimationFrame(() => requestAnimationFrame(() => resolve({
        width: Number(document.documentElement.dataset.width),
        height: Number(document.documentElement.dataset.height),
        errors: document.querySelectorAll('i[data-icon]').length })))
    : setTimeout(poll, 50);
  poll();
})"""


def shoot(chrome, page, query, output, size=None, width=None):
    url = (PREVIEW / page).as_uri() + "?" + "&".join(filter(None, [query, "capture"]))
    viewport = size or (width, 900)
    chrome.call("Emulation.setDeviceMetricsOverride", session=True, width=viewport[0], height=viewport[1],
                deviceScaleFactor=SCALE, mobile=False)
    chrome.call("Page.navigate", session=True, url=url)
    chrome.wait_event("Page.loadEventFired")
    state = chrome.evaluate(READY)
    if state["errors"]:
        fail(f"{page}?{query}: {state['errors']} icon(s) failed to render")
    if size is None:
        size = (max(width, state["width"]), state["height"])
        chrome.call("Emulation.setDeviceMetricsOverride", session=True, width=size[0], height=size[1],
                    deviceScaleFactor=SCALE, mobile=False)
        chrome.evaluate("new Promise(r => requestAnimationFrame(() => requestAnimationFrame(r)))")
    shot = chrome.call("Page.captureScreenshot", session=True, format="png", fromSurface=True)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_bytes(base64.b64decode(shot["data"]))
    print(f"wrote {output.relative_to(ROOT)} ({size[0]}×{size[1]} @{SCALE}x)")


def section_ids(page):
    source = (PREVIEW / page).read_text(encoding="utf-8")
    return re.findall(r'<section[^>]*data-section[^>]*id="([A-Za-z]+)"', source)


def screenshot_jobs():
    """Yield (group, name, page, query, output, size, width) for every image."""
    # Foundations show both themes side by side where it matters, so they are captured in Dark only.
    for section in section_ids("index.html"):
        yield ("foundations", section, "index.html", f"only={section}&theme=dark",
               IMAGES / "foundations" / f"{section}.png", None, FOUNDATIONS_WIDTH)
    for component in section_ids("components.html"):
        for theme in THEMES:
            yield ("components", component, "components.html", f"only={component}&theme={theme}",
                   IMAGES / "components" / f"{component}-{theme}.png", None, COMPONENT_WIDTH)
    for name, page, query, themes in SCREENS:
        for theme in themes:
            yield ("screens", name, page, "&".join(filter(None, [query, f"theme={theme}"])),
                   IMAGES / "screens" / f"{name}-{theme}.png", SCREEN_SIZE, None)


def cmd_screenshots(selected):
    """Render all images, or only the groups / names given (e.g. `screens`, `motion`, `Button`)."""
    jobs = [job for job in screenshot_jobs() if not selected or job[0] in selected or job[1] in selected]
    if not jobs:
        fail("nothing matches: " + " ".join(sorted(selected)))
    binary = chrome_binary()
    with tempfile.TemporaryDirectory() as profile:
        chrome = Chrome(binary, profile)
        try:
            for _group, _name, page, query, output, size, width in jobs:
                shoot(chrome, page, query, output, size=size, width=width)
        finally:
            chrome.close()
    if not selected:
        expected = {job[4] for job in jobs}
        for stale in sorted(set(IMAGES.rglob("*.png")) - expected):
            stale.unlink()
            print(f"removed {stale.relative_to(ROOT)}")


def main():
    if len(sys.argv) < 2:
        fail(__doc__.strip().splitlines()[0] + " — see --help")
    command, rest = sys.argv[1], sys.argv[2:]
    if command in ("-h", "--help"):
        print(__doc__)
    elif command == "render":
        cmd_render()
    elif command == "check":
        cmd_check()
    elif command == "vendor-icons":
        cmd_vendor_icons()
    elif command == "fonts":
        cmd_fonts()
    elif command == "screenshots":
        cmd_screenshots(set(rest))
    else:
        fail(f"unknown command: {command}")


if __name__ == "__main__":
    main()
