[package]
name = "kronello-vector"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["float_roundtrip"] }
schemars = "1"
kronello-model = { path = "../kronello-model" }
kurbo = "0.13.1"
thiserror = "2"

[dev-dependencies]
kronello-eval = { path = "../kronello-eval" }
kronello-time = { path = "../kronello-time" }
serde_json = { version = "1", features = ["float_roundtrip"] }

[lints]
workspace = true
